import seaborn as sns
def set_graph_style():
    sns.set_style('ticks', {'axes.facecolor': 'white',
                             'axes.edgecolor': '.15',
                             'axes.grid': True,
                             'axes.axisbelow': True,
                             'axes.labelcolor': '.15',
                             'figure.facecolor': 'white',
                             'grid.color': '.8',
                             'grid.linestyle': '-',
                             'text.color': '.15',
                             'xtick.color': '.15',
                             'ytick.color': '.15',
                             'xtick.direction': 'out',
                             'ytick.direction': 'out',
                             'lines.solid_capstyle': 'round',
                             'patch.edgecolor': 'w',
                             'image.cmap': 'rocket',
                             'font.family': ['sans-serif'],
                             'font.sans-serif': ['Arial',
                              'DejaVu Sans',
                              'Liberation Sans',
                              'Bitstream Vera Sans',
                              'sans-serif'],
                             'patch.force_edgecolor': True,
                             'xtick.bottom': True,
                             'xtick.top': False,
                             'ytick.left': True,
                             'ytick.right': False,
                             'axes.spines.left': True,
                             'axes.spines.bottom': True,
                             'axes.spines.right': True,
                             'axes.spines.top': True})
    sns.set_context("notebook", font_scale=1.6)